apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: argo-hello
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: argo-hello
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: argo-hello
  name: argo-hello
spec:
  containers:
  - image: yousuf64/argocd-app:2.0
    name: argo-hello
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}